version: 0.1.{build}

# Fix line endings on windows
init:  
 - git config --global core.autocrlf true
 
before_build:
- cd src
- nuget restore
- cd ..

build:
  verbosity: minimal
  
 # enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "0.1.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"